### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by NatalieDowling** [shcaba/DL-Mapper#11]
Plot title "Comparison of attribute scores across examples fisheries" should be "example fisheries"
The hover description for the data attribute "types" has "abundnace" rather than "abundance"
The hover description for the data attribute "imprecision" has "varaiance" rather than "variance"

I wonder if the threshold boxes' titles should be the same as the Guidance options titles on the plot of strategic guidance, too.

**Comment by shcaba** [comment]
I addressed most of these other than the titles matching the Guidance options. We are going to get rid of the threshold boxes once we settle on values, so those are just there for our debugging purposes and will go away. Let me know if that doesn't make sense.
